# frozen_string_literal: true
# Step definitions for LME Matching Rules
# Generated by LME-Testing BDD Pipeline
# WARNING: Review and customize before production use

# ============================================================
# Session & Authentication Steps
# ============================================================

Given(/^a registered_intermediating_broker submits a document containing capitalised terms$/) do
  @broker = LME::Client.registered_intermediary
  @document = LME::API.create_document(broker: @broker, terms: :capitalised)
end

Given(/^the terms are not otherwise defined within the document$/) do
  @document.terms_defined = false
  @document.terms_conflict = false
end

Given(/^the terms are defined differently than in the LME Rulebook$/) do
  @document.terms_defined = true
  @document.terms_conflict = true
end

# ============================================================
# Terminology Validation Steps
# ============================================================

When(/^the system processes the document terminology$/) do
  @validation_result = LME::API.validate_terminology(@document)
end

Then(/^the terms are assigned the meaning ascribed in the LME Rulebook$/) do
  expect(@validation_result.compliant).to be(true)
  expect(@validation_result.source).to eq('LME Rulebook')
end

Then(/^the obligation is fulfilled$/) do
  expect(@validation_result.status).to eq('fulfilled')
end

Then(/^the system identifies the deviation from the LME Rulebook$/) do
  expect(@validation_result.compliant).to be(false)
  expect(@validation_result.errors).to include('TERM_DEVIATION')
end

Then(/^the obligation is not fulfilled$/) do
  expect(@validation_result.status).to eq('rejected')
end

# ============================================================
# Matching Rules Adoption Steps
# ============================================================

Given(/^the Exchange defines matching rules$/) do
  @rules = LME::PostTrade.define_matching_rules(version: '1.0')
end

When(/^the rules are submitted for adoption$/) do
  @adoption_status = LME::PostTrade.submit_adoption(@rules)
end

Then(/^the rules are recognized as part of Administrative Procedures$/) do
  expect(@adoption_status.adopted).to be(true)
  expect(@adoption_status.classification).to eq('Administrative_Procedures')
end

# ============================================================
# Price Validation Steps
# ============================================================

Given(/^business is transacted on the Exchange$/) do
  @session = LME::Client.login(
    username: ENV['LME_USERNAME'] || 'test_trader',
    password: ENV['LME_PASSWORD'] || 'test_pass'
  )
end

When(/^trade agreement occurs$/) do
  @trade_agreement = LME::PostTrade.create_agreement
end

Then(/^business is subject to price validation$/) do
  expect(@trade_agreement.price_validation_required).to be(true)
end

Given(/^an order or trade fails the price validation check$/) do
  @order_params = {
    price: '999999',  # Intentionally invalid for prototype
    metal: 'ALU',
    quantity: 25,
    delivery_date: '2024-03-27'
  }
  @validation_result = LME::API.check_price_validation(@order_params)
  expect(@validation_result.status).to eq('FAILED')
end

When(/^the Member contacts the Exchange to explain the rationale for the price$/) do
  @contact_response = LME::PostTrade.contact_exchange(
    reason: @validation_result.rejection_reason
  )
end

Then(/^the processing result indicates compliance$/) do
  # Verify the contact was recorded
  expect(@contact_response).not_to be_nil
  expect(@contact_response.status).to eq('RECORDED')

  # Verify compliance status
  compliance = LME::PostTrade.get_compliance_status(@validation_result.rejection_reason)
  expect(compliance).to eq('COMPLIANT')
end

When(/^the Member does not contact the Exchange to explain the rationale for the price$/) do
  @contact_response = nil  # Simulates member not contacting
end

Then(/^the processing result indicates non-compliance or failure$/) do
  expect(@contact_response).to be_nil

  compliance = LME::PostTrade.get_compliance_status('trade_without_contact')
  expect(compliance).to eq('NON_COMPLIANT')
end

# ============================================================
# Trade Re-submission Steps (Failed Checks)
# ============================================================

Given(/^trade submission resulted in Failed Checks$/) do
  @trade_params = {
    price: '999999',
    metal: 'ALU',
    quantity: 25
  }
  @trade_submission = LME::API.submit_trade(@trade_params)
  expect(@trade_submission.status).to eq('SUBMITTED')
end

Given(/^Exchange requested additional information$/) do
  @info_request = LME::PostTrade.get_info_request(@trade_submission.id)
  expect(@info_request).not_to be_nil
end

Given(/^Member provided the requested additional information$/) do
  LME::PostTrade.provide_info(
    @trade_submission.id,
    { price_explanation: 'Market volatility adjustment' }
  )
end

When(/^Member requests to re-submit the trade in its original form$/) do
  @resubmission_response = LME::API.resubmit_trade(
    @trade_submission.id,
    original_form: @trade_params
  )
end

Then(/^system permits the trade re-submission$/) do
  expect(@resubmission_response.status).to eq('PERMITTED')
end

Then(/^validation result indicates acceptance$/) do
  expect(@resubmission_response.validation_result).to eq('ACCEPTED')
end

# ============================================================
# Venue-specific Steps
# ============================================================

Given(/^LME trading environment is active$/) do
  @env = LME::Client.environment
  expect(@env.status).to eq('active')
end

When(/^trade agreement occurs on any venue$/) do
  @agreement = LME::PostTrade.create_agreement
end

Then(/^trade is subject to price validation$/) do
  expect(@agreement.price_validation_required).to be(true)
end
