$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$handoffPath = Join-Path $repoRoot 'docs\session_handoff.md'

$branch = (git -C $repoRoot branch --show-current).Trim()
if (-not $branch) {
    $branch = 'unknown'
}

$recentCommitSubjects = @(git -C $repoRoot log -5 --pretty=format:%s)
$generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")

$recentCommitsBlock = if ($recentCommitSubjects.Count -gt 0) {
    ($recentCommitSubjects | ForEach-Object { "- ``$_``" }) -join [Environment]::NewLine
} else {
    "- No commits found"
}

$template = @'
# Session Handoff

> This file is auto-generated by `scripts/update_session_handoff.ps1`.
> It is refreshed on commit when local git hooks are enabled.

## Purpose

This file is a short handoff for continuing work on another machine or in a fresh AI session.

It captures the current repo state, the most relevant documents, the recent change direction, and the recommended next step.

Generated at:

- `{0}`

---

## Read First

Before making substantial changes, read these files in order:

1. `AGENTS.md`
2. `README.md`
3. `docs/index.md`
4. `docs/roadmap.md` (v3.0 — Stage M complete, Stage 2 Direction A underway)
5. `docs/implementation_plan.md` (v3.0)
6. `docs/acceptance.md`
7. `docs/architecture.md` (v3.0)

If the task touches model or prompt behavior, also read:

- `docs/model_governance.md`
- `docs/prompt_lifecycle.md`
- `docs/agent_guidelines.md`

If the task touches extraction or rule artifacts, also read:

- `docs/rule_extraction_script_guide.md`
- `docs/rule_model_and_parsing_design.md`

---

## Current Branch and Recent Commit Direction

Current branch:

- `{1}`

Recent commit subjects:

{2}

---

## What Was Just Done

Recent completed work:

- **S2-T01 v1.1 checker re-run (2026-04-20)**
  - Prompt calibration (v1.1): workflow+exception, deadline+boundary, prohibition+positive guidelines
  - Result: 72.22% -> 75.0% coverage (+2.78%)
  - 9 rules improved (partial->full), 4 rules regressed (full->partial)
  - Net: +5 fully covered rules (130->135), 12 partially covered, 1 uncovered
  - Root cause: remaining failures are maker quality issues, not checker calibration
  - Artifacts: `runs/checker/20260420T062527Z/`, `evidence/20260420_s2t01_v1p1_checker_run/`
  - Analysis: `docs/s2t01_coverage_analysis.md` (updated with v1.1 results)

- **S2-T02 checker stability measurement** (v1→v4 iterations, 2026-04-19)
  - v1/v2: Silent truncation — pipeline misreported completion with 14/64 of 322 cases processed
  - v3 fix: Error surfacing (`batches_processed`/`failed_batch_num`) in `pipelines.py`; 60% instability (10 comparable cases)
  - v4 fix: Retry logic (`providers.py`, max_retries=3, exponential backoff); Run A improved 63→121 batches (+92%)
  - v4 outcome: Run B process hung at batch 98; full stability_report not produced
  - **Conclusion: API network unreliability blocks full 322-case measurement; instability directionally >> 10% threshold**
  - Artifacts: `runs/checker-stability/20260418T231915+0800-v4/`

- **Code fixes committed:**
  - `pipelines.py`: error surfacing with remaining count on exception
  - `providers.py`: retry loop for transient errors (SSL EOF, connection reset, HTTP 5xx)
  - `prompts.py`: CHECKER_PROMPT_VERSION 1.0->1.1, coverage_relevance guidelines

- **Cleanup (2026-04-19):** Evidence preserved in `evidence/` (~1.3MB). Deleted: `vendor/` (1.7MB), `logs-from-backup-run/` (37KB), `reports/` (2.1MB), stale runs/ artifacts (~4.3MB)
- **Stage M COMPLETE (2026-04-19):** SM-T01~SM-T05 all done — UTC timestamps, workflow interrupt handling, retry config merged from master

---

## Current Repo State

**Stage M (master branch merge) COMPLETED 2026-04-19.** All Stage 1 work is complete. Stage 2 Direction A is underway.

Key repo state:

- `pipelines.py` + `providers.py`: error surfacing and retry logic implemented
- `prompts.py`: CHECKER_PROMPT_VERSION 1.1 with coverage_relevance calibration guidelines
- `evidence/` directory: preserved key artifacts (stability v4, baseline full, governance signals, S2-T01 v1.1 run)
- `vendor/`, `logs-from-backup-run/`, `reports/` deleted (gitignored or archived evidence)
- Phase 1/2/3 acceptance gates all marked complete in `docs/acceptance.md`

Governance checks available:

- `python scripts/check_docs_governance.py`
- `python scripts/check_artifact_governance.py`
- `python scripts/validate_rules.py` (upstream validation in CI)

---

## Recommended Next Step

**Stage M complete. Stage 2 Direction A is the focus:**

1. **Maker v1.3**: Fix prohibition positive semantic misalignment (test prohibited action, not permitted action)
2. **S2-T01 v1.1 done**: Coverage 72.22% -> 75.0% (+2.78%). v1.2 calibration limited (regressions); maker needed for remaining patterns
3. **S2-T02 resolved**: Error surfacing + retry logic committed; 60-71% instability observed due to API random disconnects
4. **S2-B1/B2**: audit_trail.py + case_compare.py implemented (optional features)

---

## Important Constraints

- Do not weaken docs or artifact governance checks silently.
- Do not introduce a new LLM-driven stage without a defined contract.
- Do not treat `semantic_rule` as a substitute for planner outputs, normalized BDD, or execution-ready artifacts.
- Do not reintroduce absolute local paths in Markdown files.
- Do not mix future enterprise or platform assumptions into current baseline work unless explicitly requested.
- Every commit should refresh `docs/session_handoff.md`; if hooks are unavailable, run the update script manually before committing.

---

## Reference Material

- `docs/roadmap.md` — current Stage 2 priorities
- `docs/architecture.md` — system architecture and module boundaries
- `docs/references/Claude-roadmap-compare.md` — historical comparison

Treat reference files as non-normative unless their content is promoted into the official docs.
'@

$content = $template -f $generatedAt, $branch, $recentCommitsBlock

Set-Content -LiteralPath $handoffPath -Value $content -Encoding utf8
