$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$handoffPath = Join-Path $repoRoot 'docs\session_handoff.md'

$branch = (git -C $repoRoot branch --show-current).Trim()
if (-not $branch) {
    $branch = 'unknown'
}

$recentCommitSubjects = @(git -C $repoRoot log -5 --pretty=format:%s)
$generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")

$recentCommitsBlock = if ($recentCommitSubjects.Count -gt 0) {
    ($recentCommitSubjects | ForEach-Object { "- ``$_``" }) -join [Environment]::NewLine
} else {
    "- No commits found"
}

$template = @'
# Session Handoff

> This file is auto-generated by `scripts/update_session_handoff.ps1`.
> It is refreshed on commit when local git hooks are enabled.

## Purpose

This file is a short handoff for continuing work on another machine or in a fresh AI session.

It captures the current repo state, the most relevant documents, the recent change direction, and the recommended next step.

Generated at:

- `{0}`

---

## Read First

Before making substantial changes, read these files in order:

1. `AGENTS.md`
2. `README.md`
3. `docs/index.md`
4. `docs/roadmap.md`
5. `docs/implementation_plan.md`
6. `docs/acceptance.md`
7. `docs/architecture.md`

If the task touches model or prompt behavior, also read:

- `docs/model_governance.md`
- `docs/prompt_lifecycle.md`
- `docs/agent_guidelines.md`

If the task touches extraction or rule artifacts, also read:

- `docs/rule_extraction_script_guide.md`
- `docs/rule_model_and_parsing_design.md`

---

## Current Branch and Recent Commit Direction

Current branch:

- `{1}`

Recent commit subjects:

{2}

---

## Current Repo State

The docs system has been aligned around a governance-contract-first approach.

Key outcomes:

- the roadmap, implementation plan, acceptance, architecture, model governance, testing governance, prompt lifecycle, and agent guidance docs are aligned
- `step_integration_plan.md` is clearly treated as a future bridge, not a current baseline shortcut
- extraction and rule-model docs were rewritten to match the current phase boundaries
- `AGENTS.md` exists as a repo entry file for AI coding agents

The repo now has two separate governance checks:

- `python scripts/check_docs_governance.py`
- `python scripts/check_artifact_governance.py`

These are wired into CI as separate jobs:

- `Docs Governance`
- `Artifact Governance`

---

## What Was Just Done

This repo recently established:

- aligned governance docs and entry docs
- split docs governance and artifact governance checks
- CI wiring for both governance checks
- a reference-material boundary policy
- a handoff file intended to make cross-machine continuation easier

---

## Current Baseline Commands

Run these before or after substantial changes:

```powershell
python scripts/check_docs_governance.py
python scripts/check_artifact_governance.py
```

If `python` is not available on `PATH`, use the local Python executable path for the same commands.

Unit test for governance checks:

```powershell
python -m unittest tests.test_docs_governance -v
```

To enable automatic handoff refresh on commit in a fresh clone:

```powershell
powershell -ExecutionPolicy Bypass -File scripts/setup_git_hooks.ps1
```

---

## Recommended Next Step

The best next step is to move from lightweight artifact governance checks to formal artifact contracts.

Recommended implementation order:

1. add formal schema files for `atomic_rule` and `semantic_rule`
2. wire schema validation into extraction scripts
3. connect schema validation into CI
4. add a few negative tests for malformed artifacts

Suggested target files or areas:

- `schemas/atomic_rule.schema.json`
- `schemas/semantic_rule.schema.json`
- `scripts/extract_matching_rules.py`
- `scripts/generate_semantic_rules.py`
- tests for invalid artifact shapes

---

## Important Constraints

- Do not weaken docs or artifact governance checks silently.
- Do not introduce a new LLM-driven stage without a defined contract.
- Do not treat `semantic_rule` as a substitute for planner outputs, normalized BDD, or execution-ready artifacts.
- Do not reintroduce absolute local paths in Markdown files.
- Do not mix future enterprise or platform assumptions into current baseline work unless explicitly requested.
- Every commit should refresh `docs/session_handoff.md`; if hooks are unavailable, run the update script manually before committing.

---

## Reference Material

If comparison context is needed, see:

- `docs/references/Claude-roadmap-compare.md`

Treat reference files as non-normative unless their content is promoted into the official docs.
'@

$content = $template -f $generatedAt, $branch, $recentCommitsBlock

Set-Content -LiteralPath $handoffPath -Value $content -Encoding utf8
