$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$handoffPath = Join-Path $repoRoot 'docs\session_handoff.md'

$branch = (git -C $repoRoot branch --show-current).Trim()
if (-not $branch) {
    $branch = 'unknown'
}

$recentCommitSubjects = @(git -C $repoRoot log -5 --pretty=format:%s)
$generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")

$recentCommitsBlock = if ($recentCommitSubjects.Count -gt 0) {
    ($recentCommitSubjects | ForEach-Object { "- ``$_``" }) -join [Environment]::NewLine
} else {
    "- No commits found"
}

$template = @'
# Session Handoff

> This file is auto-generated by `scripts/update_session_handoff.ps1`.
> It is refreshed on commit when local git hooks are enabled.

## Purpose

This file is a short handoff for continuing work on another machine or in a fresh AI session.

It captures the current repo state, the most relevant documents, the recent change direction, and the recommended next step.

Generated at:

- `{0}`

---

## Read First

Before making substantial changes, read these files in order:

1. `AGENTS.md`
2. `README.md`
3. `docs/index.md`
4. `docs/roadmap.md` (v3.1 - Stage 2 complete, mock execution bridge added)
5. `docs/implementation_plan.md` (v3.0)
6. `docs/acceptance.md`
7. `docs/architecture.md` (v3.1)

If the task touches model or prompt behavior, also read:

- `docs/model_governance.md`
- `docs/prompt_lifecycle.md`
- `docs/agent_guidelines.md`

If the task touches extraction or rule artifacts, also read:

- `docs/rule_extraction_script_guide.md`
- `docs/rule_model_and_parsing_design.md`

---

## Current Branch and Recent Commit Direction

Current branch:

- `{1}`

Recent commit subjects:

{2}

---

## What Was Just Done

Recent completed work:

- **S2-T01 v1.5 maker + checker run (2026-04-21)**
  - MAKER_PROMPT_VERSION 1.4 -> 1.5, CHECKER_PROMPT_VERSION 1.2 -> 1.3
  - Deadline positive/negative calibration: deadline+positive and deadline+negative now DIRECT
  - Regression guardrail added: don't lower evidence_consistency for edge-case scenarios
  - Coverage: 78.89% (142 fully covered, 5 partial, 1 uncovered)
  - Net: +12 fully covered rules from baseline (130->142), +6.67pp (72.22%->78.89%)
  - SR-MR-070-02 fully covered (deadline negative calibration)
  - Remaining gaps: SR-MR-015-B3-4 (boundary, evidence-constrained), SR-MR-071-C-1 (LLM non-determinism)
  - Artifacts: `runs/maker/20260421T074319Z/`, `runs/checker/20260421T083003Z/`

- **S2-B1/B2 integration (2026-04-21)**
  - `review_session.py` finalize_session() now calls build_audit_trail -> final/audit_trail.html
  - _run_job() now calls build_case_compare after rewrite -> iter<N>/rewrite/case_compare.html
  - Both gracefully degrade on failure (non-blocking)
  - audit_trail.py (267 lines) + case_compare.py (216 lines) now fully wired

- **S2-C1 mock API execution bridge (2026-04-23)**
  - Added standalone HTTP mock API based on `docs/materials/LME_Matching_Rules_Aug_2022.md`
  - Added executable BDD feature, Python step definitions, lightweight runner, tests, README, and zip deliverable
  - Deliverables: `deliverables/lme_mock_api/`, `deliverables/lme_mock_api.zip`
  - Validation: `python run_bdd.py` -> 33 passed, 0 failed; `python -m unittest tests.test_mock_api` -> 2 tests OK

- **S2-T01 v1.4 maker + checker run (2026-04-21)**
  - MAKER_PROMPT_VERSION 1.3 -> 1.4, CHECKER_PROMPT_VERSION 1.1 -> 1.2
  - Prohibition negative calibration: negative case for prohibition is DIRECT
  - SR-MR-033-03 and SR-MR-033-04 both fully covered
  - Coverage: 77.22% (139 fully covered)
  - Artifacts: `runs/maker/20260421T012618Z/`, `runs/checker/20260421T030325Z/`

- **Cleanup (2026-04-19):** Evidence preserved in `evidence/` (~1.3MB). Deleted: `vendor/` (1.7MB), `logs-from-backup-run/` (37KB), `reports/` (2.1MB), stale runs/ artifacts (~4.3MB)
- **Stage M COMPLETE (2026-04-19):** SM-T01~SM-T05 all done - UTC timestamps, workflow interrupt handling, retry config merged from master

---

## Current Repo State

**Stage M (master branch merge) COMPLETED 2026-04-19.** Stage 2 Direction A (S2-T01) COMPLETE. S2-B1/B2 INTEGRATED. S2-C1 MOCK API EXECUTION BRIDGE COMPLETE.

Key repo state:

- `prompts.py`: MAKER_PROMPT_VERSION 1.5, CHECKER_PROMPT_VERSION 1.3 with full coverage_relevance calibration
- S2-T01 coverage: 78.89% (142/180 fully covered) - practical ceiling with current evidence
- `audit_trail.py` + `case_compare.py`: fully wired into `review_session.py`
- `pipelines.py` + `providers.py`: error surfacing and retry logic implemented
- Evidence preserved in `evidence/` directory
- Mock API bridge preserved in `deliverables/lme_mock_api/` and documented in `docs/mock_api_validation_plan.md`
- Phase 1/2 acceptance gates are updated in `docs/acceptance.md`; Stage 3 real LME API remains blocked

Governance checks available:

- `python scripts/check_docs_governance.py`
- `python scripts/check_artifact_governance.py`
- `python scripts/validate_rules.py` (upstream validation in CI)

---

## Recommended Next Step

**Stage 2 complete (S2-T01 at 78.89%, S2-B1/B2 integrated). Remaining:**

1. **Decide whether to keep `deliverables/lme_mock_api/` as a long-lived sample or move it under a future `samples/`/`tools/` path.**
2. **LLM non-determinism stabilization**: SR-MR-015-B3-4 boundary and SR-MR-071-C-1 negative still fluctuate - multi-run voting or consolidated scenario design.
3. **Stage 3**: Blocked on LME VM access (ETA unknown); replace mock API target with real LME API when access is available.

---

## Important Constraints

- Do not weaken docs or artifact governance checks silently.
- Do not introduce a new LLM-driven stage without a defined contract.
- Do not treat `semantic_rule` as a substitute for planner outputs, normalized BDD, or execution-ready artifacts.
- Do not reintroduce absolute local paths in Markdown files.
- Do not mix future enterprise or platform assumptions into current baseline work unless explicitly requested.
- Every commit should refresh `docs/session_handoff.md`; if hooks are unavailable, run the update script manually before committing.

---

## Reference Material

- `docs/roadmap.md` - current Stage 2 priorities
- `docs/architecture.md` - system architecture and module boundaries
- `docs/mock_api_validation_plan.md` - S2-C1 mock execution bridge
- `docs/references/Claude-roadmap-compare.md` - historical comparison

Treat reference files as non-normative unless their content is promoted into the official docs.
'@

$content = $template -f $generatedAt, $branch, $recentCommitsBlock

Set-Content -LiteralPath $handoffPath -Value $content -Encoding utf8
